name: Pet-Store

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
        - name: Install Node
          uses: actions/setup-node@v3
          with: 
            node-version: '18.18.0'
        
        - name: Install newman
          run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

        - name: Make directory for results
          run: mkdir -p testResults

        - name: Run Postman collection
          run: |
             newman run petstore.collection.json -r html extra --reporter-htmlextra-export testResults/htmlreport.html

        - name: Output the run Details
          uses: actions/upload-artifact@v2
          with:
               name: RunReports
               path: testResults
